# Generated by Django 5.0.3 on 2026-03-18 07:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total exam duration (e.g., 170 mins for VSTEP)')),
                ('total_marks', models.DecimalField(decimal_places=2, default=10.0, help_text='Total score out of 10', max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('directions', models.TextField(blank=True)),
                ('passage_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='exams/media/listening/')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Board of Education (Admin)'), ('EXAMINER', 'Expert (Examiner)'), ('TEACHER', 'Candidate (Teacher)')], default='TEACHER', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADING', 'Grading Queue'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('consolidated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TFNG', 'True / False / Not Given'), ('MATCHING', 'Matching'), ('TEXT_LONG', 'Writing Text Area'), ('AUDIO_REC', 'Speaking Audio Record')], max_length=20)),
                ('prompt', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('prep_time_seconds', models.PositiveIntegerField(default=0, help_text='Time to prepare before speaking')),
                ('response_time_seconds', models.PositiveIntegerField(default=0, help_text='Time limit for audio recording')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.part')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('LISTENING', 'Listening'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=15)),
                ('order', models.PositiveIntegerField(help_text='Typical VSTEP: 1:L, 2:R, 3:W, 4:S')),
                ('time_limit_minutes', models.PositiveIntegerField(help_text='E.g., 40 mins for Listening, 60 mins for Reading')),
                ('total_marks', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.section'),
        ),
        migrations.CreateModel(
            name='SectionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_submissions', to='core.examsubmission')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='submissions/speaking/')),
                ('is_graded', models.BooleanField(default=False, help_text='Becomes True once AI or Human grades it')),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grader_comments', models.TextField(blank=True)),
                ('ai_feedback', models.JSONField(blank=True, help_text='Stores grammar/fluency metrics from AI agent', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('section_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.sectionsubmission')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice')),
            ],
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['status'], name='core_examsu_status_3c2ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['user', 'status'], name='core_examsu_user_id_ac70b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('user', 'exam')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['part', 'order'], name='core_questi_part_id_652ec2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('exam', 'section_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionsubmission',
            unique_together={('exam_submission', 'section')},
        ),
        migrations.AddIndex(
            model_name='teacherresponse',
            index=models.Index(fields=['is_graded', 'question'], name='core_teache_is_grad_a3d9e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherresponse',
            unique_together={('section_submission', 'question')},
        ),
    ]
