# Generated by Django 5.0.3 on 2026-03-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacherresponse_ai_evaluation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherresponse',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Just submitted'), ('AI_PROCESSING', 'AI Processing'), ('READY_FOR_GRADING', 'Ready for Grading'), ('COMPLETED', 'Graded')], default='PENDING', max_length=20),
        ),
    ]
