upstream smartexam_web {
    server web:8000;
}

server {
    listen 80;

    # Increase max body size for audio file uploads (Speaking section)
    # Default is 1M, let's bump it to 50M
    client_max_body_size 50M;

    location / {
        proxy_pass http://smartexam_web;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        # Serve static media fast, which is crucial for the Listening section
        # Enable caching headers for audio files
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
